// GENERATED by scripts/build-cjs.js — DO NOT EDIT. Source of truth: codemix.js
/**
 * Codemix Skill — CommonJS Engine & Module
 * Generated automatically from codemix.js (Single Source of Truth).
 */

// Closed vocabulary for Customer Support English
const EN_WORDS = new Set(`the a an and or but so if not no yes is are am was were be been being have has had do does did
i me my mine you your yours he she it we us our they them their this that these those there here
can could will would should shall may might must need want got get give gave take took make made
please sorry thanks thank hello hi hey ok okay well just still already again very really too also
from to for with on in at of by about after before since until while than then when what why how where who
last next this week month year day days today tomorrow yesterday morning evening night time times hours minutes
order orders tracking track delivery deliver delivered shipment shipped courier parcel package
refund refunded return returns replace replacement exchange cancel cancelled cancellation
payment pay paid card cards bank account amount money charge charged charges transaction invoice bill billing
login log password reset link expire expired expiry otp verify verification
update updated status support help ticket complaint issue problem service customer agent number id
app website page email phone call message product item address pin code upi emi wallet recharge plan network signal
check checking checked show shows showing deducted response initiate arrange escalate confirm confirmed
one two three four five six seven eight nine ten first second boss sir madam`.trim().split(/\s+/));

// Native Indic Unicode Script Ranges
const INDIC_SCRIPTS = [
  ["Tamil", /[\u0B80-\u0BFF]/],
  ["Hindi", /[\u0900-\u097F]/],
  ["Bengali", /[\u0980-\u09FF]/],
  ["Telugu", /[\u0C00-\u0C7F]/],
  ["Kannada", /[\u0C80-\u0CFF]/],
  ["Malayalam", /[\u0D00-\u0D7F]/],
  ["Gujarati", /[\u0A80-\u0AFF]/],
  ["Punjabi", /[\u0A00-\u0A7F]/],
  ["Odia", /[\u0B00-\u0B7F]/]
];

// Reference CRM database mock for demonstration
const CRM_ORDERS = {
  "48211": { status: "stuck at Bhiwandi hub", days: 6, carrier: "Delhivery", value: "₹2,499" },
  "33417": { status: "out for delivery", days: 1, carrier: "Ecom Express", value: "₹899" },
  "99120": { status: "duplicate charge confirmed", days: 2, carrier: "—", value: "₹1,299" },
  "55102": { status: "damaged in transit reported", days: 3, carrier: "Blue Dart", value: "₹4,150" },
  "77841": { status: "cancelled by customer", days: 4, carrier: "Shadowfax", value: "₹1,850" }
};

// Weighted Score-Based Intent Rules
const INTENT_RULES = [
  {
    id: "delivery_delay",
    name: "Order not delivered, tracking stale",
    action: "Check carrier, offer reship or refund",
    priority: "P2",
    subject: "Delivery delay reported by customer",
    weights: [
      { kw: ["deliver", "delivery", "delivered", "pahuncha", "vandhadhu", "reach"], w: 4 },
      { kw: ["tracking", "track", "status", "shipment"], w: 4 },
      { kw: ["parcel", "package", "courier", "order"], w: 2 },
      { kw: ["abhi tak", "nahi hua", "not received", "kahan hai", "varala", "stuck", "late", "delay"], w: 3 }
    ]
  },
  {
    id: "billing_dispute",
    name: "Duplicate charge, refund requested",
    action: "Verify transaction, initiate refund",
    priority: "P1",
    subject: "Duplicate charge and refund request",
    weights: [
      { kw: ["charge", "charged", "charges", "kat gaya", "debited", "debit", "double billing"], w: 4 },
      { kw: ["double", "do baar", "twice", "2 times", "duplicate"], w: 4 },
      { kw: ["bank", "transaction", "invoice", "statement", "card", "wallet"], w: 3 },
      { kw: ["refund", "refunded", "paisa wapas", "panam", "kaasu"], w: 3 },
      { kw: ["காசு", "பணம்", "பைசா", "पैसा", "पैसे", "रिफंड", "টাকা", "డబ్బు", "ಹಣ", "പണം"], w: 4 }
    ]
  },
  {
    id: "cancellation_refund",
    name: "Cancelled order, amount still deducted",
    action: "Confirm cancellation, release funds",
    priority: "P1",
    subject: "Refund pending after cancellation",
    weights: [
      { kw: ["cancel", "cancelled", "cancellation", "radd"], w: 4 },
      { kw: ["deducted", "amount", "money", "paise", "kat gaye", "reflect"], w: 3 },
      { kw: ["still shows", "wapas", "refund", "pending", "account"], w: 3 }
    ]
  },
  {
    id: "account_access",
    name: "Cannot log in, reset link expired",
    action: "Send fresh reset link, verify identity",
    priority: "P2",
    subject: "Login blocked by expired reset link",
    weights: [
      { kw: ["login", "log in", "signin", "sign in", "account access", "unlock"], w: 4 },
      { kw: ["password", "passcode", "pin", "credential"], w: 4 },
      { kw: ["reset", "reset link", "link expired", "expiry"], w: 4 },
      { kw: ["otp", "verify", "verification", "blocked", "mudiyala", "locked", "authentication"], w: 3 }
    ]
  },
  {
    id: "damaged_item",
    name: "Damaged product received, replacement needed",
    action: "Authorize return, issue replacement dispatch",
    priority: "P2",
    subject: "Damaged goods replacement request",
    weights: [
      { kw: ["damaged", "broken", "damage", "toota", "kharab", "defect", "faulty", "swollen"], w: 5 },
      { kw: ["replace", "replacement", "exchange", "badal", "return"], w: 4 },
      { kw: ["product", "item", "box", "package", "saman", "battery"], w: 2 }
    ]
  },
  {
    id: "agent_behaviour",
    name: "Support agent misbehaviour or abrupt disconnection",
    action: "Escalate to supervisor, review call recording",
    priority: "P1",
    subject: "Customer complaint regarding support agent behaviour",
    weights: [
      { kw: ["rude", "misbehave", "misbehaved", "misbehavior", "behaviour", "behavior", "attitude", "aggressively"], w: 5 },
      { kw: ["phone cut", "call cut", "disconnected", "disconnect", "hung up", "cut the call", "cut pannitanga"], w: 5 },
      { kw: ["abuse", "shouting", "bad tone", "tameez", "galat baat", "maramariyatha", "unacceptable"], w: 4 },
      { kw: ["agent", "executive", "representative", "support person", "supervisor"], w: 2 }
    ]
  },
  {
    id: "document_request",
    name: "Tax invoice or warranty document request",
    action: "Generate GST invoice copy and email to customer",
    priority: "P3",
    subject: "Tax invoice and warranty document request",
    weights: [
      { kw: ["invoice", "tax invoice", "gst invoice", "gst bill", "bill copy", "tax bill"], w: 5 },
      { kw: ["warranty", "warranty card", "warranty slip", "payment slip", "receipt download", "receipt"], w: 4 },
      { kw: ["email me", "send email", "anuppunga", "bhej do", "chahiye", "download", "mail pe", "slip"], w: 2 },
      { kw: ["order", "tax", "document", "gst"], w: 1 }
    ]
  }
];

// Tuned Baseline Dataset (20 Labelled Code-Mixed Sentences)
const BENCHMARK_DATASET = [
  {
    id: 1,
    text: "Bhaiya mera order abhi tak deliver nahi hua, tracking bhi update nahi ho raha hai. Main kal se try kar raha hoon but koi response nahi. Order number 48211 hai.",
    expected_intent_id: "delivery_delay",
    expected_lang: "Hindi",
    expected_order: "48211",
    expected_priority: "P2"
  },
  {
    id: 2,
    text: "Yaar aapne mere card se do baar charge kar diya hai, ye kya scene hai? Main bank ko complaint karunga agar aaj refund initiate nahi hua. Transaction ID 99120.",
    expected_intent_id: "billing_dispute",
    expected_lang: "Hindi",
    expected_order: "99120",
    expected_priority: "P1"
  },
  {
    id: 3,
    text: "Enna boss, en account la login panna mudiyala, password reset link vandhu expire aayiduchu. Please help pannunga, order 33417 track panna vendum.",
    expected_intent_id: "account_access",
    expected_lang: "Tamil",
    expected_order: "33417",
    expected_priority: "P2"
  },
  {
    id: 4,
    text: "So I placed the order last week, phir maine cancel kar diya but the amount still shows deducted. Can you please check, order 48211.",
    expected_intent_id: "cancellation_refund",
    expected_lang: "Hindi",
    expected_order: "48211",
    expected_priority: "P1"
  },
  {
    id: 5,
    text: "Mera parcel box totally damaged and broken condition me aaya hai. Mujhe turant replacement chahiye, item unusable hai. Order 55102.",
    expected_intent_id: "damaged_item",
    expected_lang: "Hindi",
    expected_order: "55102",
    expected_priority: "P2"
  },
  {
    id: 6,
    text: "Delivery boy call karke bola order deliver ho gaya but mujhe koi parcel nahi mila. Tracking says delivered! Order 48211.",
    expected_intent_id: "delivery_delay",
    expected_lang: "Hindi",
    expected_order: "48211",
    expected_priority: "P2"
  },
  {
    id: 7,
    text: "Bank account la irundhu two times money debited for single transaction. Refund status update pannunga please, ID 99120.",
    expected_intent_id: "billing_dispute",
    expected_lang: "Tamil",
    expected_order: "99120",
    expected_priority: "P1"
  },
  {
    id: 8,
    text: "Ami order ta cancel korechi kintu taka account e ferot asheni. Refund amount still deducted showing. Order 77841.",
    expected_intent_id: "cancellation_refund",
    expected_lang: "Bengali",
    expected_order: "77841",
    expected_priority: "P1"
  },
  {
    id: 9,
    text: "Password change panna try pannen but OTP phone ku varala, account lock aayiduchu completely. Please reset link anuppunga.",
    expected_intent_id: "account_access",
    expected_lang: "Tamil",
    expected_order: null,
    expected_priority: "P2"
  },
  {
    id: 10,
    text: "Screen broken received for electronic gadget, package was torn. Replacement dispatch arrange kijiye jaldi, order 55102.",
    expected_intent_id: "damaged_item",
    expected_lang: "Hindi",
    expected_order: "55102",
    expected_priority: "P2"
  },
  {
    id: 11,
    text: "Courier Delhivery tracking shows stuck at transit hub for 5 days. Kahan hai mera package? Order 48211.",
    expected_intent_id: "delivery_delay",
    expected_lang: "Hindi",
    expected_order: "48211",
    expected_priority: "P2"
  },
  {
    id: 12,
    text: "Duplicate payment charge ho gaya checkout pe network error ki wajah se. Paisa wapas kab aayega? Transaction 99120.",
    expected_intent_id: "billing_dispute",
    expected_lang: "Hindi",
    expected_order: "99120",
    expected_priority: "P1"
  },
  {
    id: 13,
    text: "Item cancel panni 4 days aachu, but money credited aagala bank account la. Check status for order 77841.",
    expected_intent_id: "cancellation_refund",
    expected_lang: "Tamil",
    expected_order: "77841",
    expected_priority: "P1"
  },
  {
    id: 14,
    text: "App la sign in panna mudiyala, error message says invalid credential. Password reset email send pannunga please.",
    expected_intent_id: "account_access",
    expected_lang: "Tamil",
    expected_order: null,
    expected_priority: "P2"
  },
  {
    id: 15,
    text: "Received defective item with scratch, item exchange request initiate kar do. Order 55102.",
    expected_intent_id: "damaged_item",
    expected_lang: "Hindi",
    expected_order: "55102",
    expected_priority: "P2"
  },
  {
    id: 16,
    text: "Ekhon porjonto parcel delivery hoyni, tracking details stale ache. Keno eta late hocche? Order 33417.",
    expected_intent_id: "delivery_delay",
    expected_lang: "Bengali",
    expected_order: "33417",
    expected_priority: "P2"
  },
  {
    id: 17,
    text: "Credit card bill la double charges show aagudhu same purchase ku. Bank statement attached, initiate refund for 99120.",
    expected_intent_id: "billing_dispute",
    expected_lang: "Tamil",
    expected_order: "99120",
    expected_priority: "P1"
  },
  {
    id: 18,
    text: "Main order cancel kar chuka hoon still payment amount kat gayi hai account se. Check refund for 48211.",
    expected_intent_id: "cancellation_refund",
    expected_lang: "Hindi",
    expected_order: "48211",
    expected_priority: "P1"
  },
  {
    id: 19,
    text: "Login locked because too many wrong attempts. Verification link aur OTP bhej do mera registered mobile pe.",
    expected_intent_id: "account_access",
    expected_lang: "Hindi",
    expected_order: null,
    expected_priority: "P2"
  },
  {
    id: 20,
    text: "Delivery parcel open karke dekha toh glass completely broken tha. Please send a quick replacement for order 55102.",
    expected_intent_id: "damaged_item",
    expected_lang: "Hindi",
    expected_order: "55102",
    expected_priority: "P2"
  }
];

// Extended Test Dataset (8 Sentences written alongside rules)
const HELD_OUT_DATASET = [
  {
    id: "E1",
    text: "Last executive was extremely rude and disconnect pannitanga call ah midway. Customer care supervisor kitta pesanum.",
    expected_intent_id: "agent_behaviour",
    expected_lang: "Tamil",
    expected_order: null,
    expected_priority: "P1"
  },
  {
    id: "E2",
    text: "Company GST invoice copy chahiye mujhe for input tax credit, order 48211 ka bill send kijiye mail pe.",
    expected_intent_id: "document_request",
    expected_lang: "Hindi",
    expected_order: "48211",
    expected_priority: "P3"
  },
  {
    id: "E3",
    text: "Tracking URL click panna error 404 varudhu, consignment dispatch aacha illaya therila, order 33417.",
    expected_intent_id: "delivery_delay",
    expected_lang: "Tamil",
    expected_order: "33417",
    expected_priority: "P2"
  },
  {
    id: "E4",
    text: "Aapka representative ne call pe abuse kiya jab maine double billing refund manga, this is unacceptable behavior!",
    expected_intent_id: "agent_behaviour",
    expected_lang: "Hindi",
    expected_order: null,
    expected_priority: "P1"
  },
  {
    id: "E5",
    text: "Please warranty document and payment slip courier kijiye registered address pe, order 55102.",
    expected_intent_id: "document_request",
    expected_lang: "Hindi",
    expected_order: "55102",
    expected_priority: "P3"
  },
  {
    id: "E6",
    text: "Delivery agent signature forgery karke fake delivered status update panni irukaru, no box received! 48211.",
    expected_intent_id: "delivery_delay",
    expected_lang: "Tamil",
    expected_order: "48211",
    expected_priority: "P2"
  },
  {
    id: "E7",
    text: "Online checkout transaction drop hoyeche kintu wallet theke 1299 taka deduct hoye geche instantly.",
    expected_intent_id: "billing_dispute",
    expected_lang: "Bengali",
    expected_order: null,
    expected_priority: "P1"
  },
  {
    id: "E8",
    text: "Customer care person hung up right in my face jab main complaint raise kar raha tha, phone cut kar diya.",
    expected_intent_id: "agent_behaviour",
    expected_lang: "Hindi",
    expected_order: null,
    expected_priority: "P1"
  }
];

// Expanded Blind Test Dataset (52 Labelled Sentences across Indian dialects)
const BLIND_DATASET = [
  {
    id: "B1",
    text: "Mera refund abhi tak bank account me transfer nahi hua, order cancel karke ek hafta ho gaya. ID 48211.",
    expected_intent_id: "cancellation_refund",
    expected_lang: "Hindi",
    expected_order: "48211",
    expected_priority: "P1"
  },
  {
    id: "B2",
    text: "Agent talked very aggressively and call kat diya when I asked for refund clarification. Serious action required.",
    expected_intent_id: "agent_behaviour",
    expected_lang: "English",
    expected_order: null,
    expected_priority: "P1"
  },
  {
    id: "B3",
    text: "Invoice download link email panni vidunga, audit purpose ku tax bill thevai. Order 33417.",
    expected_intent_id: "document_request",
    expected_lang: "Tamil",
    expected_order: "33417",
    expected_priority: "P3"
  },
  {
    id: "B4",
    text: "Phone battery completely swollen and defective item dispatch aayirukku. Exchange or replacement process enna? Order 55102.",
    expected_intent_id: "damaged_item",
    expected_lang: "Tamil",
    expected_order: "55102",
    expected_priority: "P2"
  },
  {
    id: "B5",
    text: "Express delivery courier parcel transit la 7 days aachu, destination ku reach aagala. Where is my shipment? 48211.",
    expected_intent_id: "delivery_delay",
    expected_lang: "Tamil",
    expected_order: "48211",
    expected_priority: "P2"
  },
  {
    id: "B6",
    text: "Mera saving account se 2 times amount deduct ho gaya hai while paying for order 99120.",
    expected_intent_id: "billing_dispute",
    expected_lang: "Hindi",
    expected_order: "99120",
    expected_priority: "P1"
  },
  {
    id: "B7",
    text: "OTP verification code SMS la receive aagala, authentication failed showing. Account access unlock pannunga.",
    expected_intent_id: "account_access",
    expected_lang: "Tamil",
    expected_order: null,
    expected_priority: "P2"
  },
  {
    id: "B8",
    text: "Ami delivery boy ke call korechilam, kintu parcel na diye phone cut kore dilo. Khub baje behavior.",
    expected_intent_id: "agent_behaviour",
    expected_lang: "Bengali",
    expected_order: null,
    expected_priority: "P1"
  },
  {
    id: "B9",
    text: "Please send original purchase receipt and GST invoice for warranty claim registration, order 48211.",
    expected_intent_id: "document_request",
    expected_lang: "English",
    expected_order: "48211",
    expected_priority: "P3"
  },
  {
    id: "B10",
    text: "Cancelled item amount refund pending since Monday, credit kab reflect hoga account me? ID 77841.",
    expected_intent_id: "cancellation_refund",
    expected_lang: "Hindi",
    expected_order: "77841",
    expected_priority: "P1"
  },
  {
    id: "B11",
    text: "Bhaiya package dispatch ho gaya but tracking status is stuck at sorting facility for 4 days. Order 48211.",
    expected_intent_id: "delivery_delay",
    expected_lang: "Hindi",
    expected_order: "48211",
    expected_priority: "P2"
  },
  {
    id: "B12",
    text: "Card transaction fail hua tha but bank statement me double billing reflect ho raha hai, order 99120.",
    expected_intent_id: "billing_dispute",
    expected_lang: "Hindi",
    expected_order: "99120",
    expected_priority: "P1"
  },
  {
    id: "B13",
    text: "Maine order radd kar diya tha yesterday, still paisa kat gaya bank se. Please initiate refund for 48211.",
    expected_intent_id: "cancellation_refund",
    expected_lang: "Hindi",
    expected_order: "48211",
    expected_priority: "P1"
  },
  {
    id: "B14",
    text: "Login attempt blocked aayiduchu, reset link email ku varala. En account unlock panni thanga.",
    expected_intent_id: "account_access",
    expected_lang: "Tamil",
    expected_order: null,
    expected_priority: "P2"
  },
  {
    id: "B15",
    text: "Product package open panni paathen, glass screen totally toota hua condition la irukku. Order 55102 replace pannunga.",
    expected_intent_id: "damaged_item",
    expected_lang: "Tamil",
    expected_order: "55102",
    expected_priority: "P2"
  },
  {
    id: "B16",
    text: "Support executive ne beech me hi phone cut kar diya when I was explaining the issue. Very rude behavior.",
    expected_intent_id: "agent_behaviour",
    expected_lang: "Hindi",
    expected_order: null,
    expected_priority: "P1"
  },
  {
    id: "B17",
    text: "Need GST invoice and tax payment slip for annual filing, please send email for order 33417.",
    expected_intent_id: "document_request",
    expected_lang: "English",
    expected_order: "33417",
    expected_priority: "P3"
  },
  {
    id: "B18",
    text: "Ecom Express courier status says delivered yesterday kintu ami kono parcel receive korini. Order 48211.",
    expected_intent_id: "delivery_delay",
    expected_lang: "Bengali",
    expected_order: "48211",
    expected_priority: "P2"
  },
  {
    id: "B19",
    text: "Credit card charged twice for single purchase at checkout, double debited amount refund kijiye ID 99120.",
    expected_intent_id: "billing_dispute",
    expected_lang: "Hindi",
    expected_order: "99120",
    expected_priority: "P1"
  },
  {
    id: "B20",
    text: "Order cancel panni two days aachu, but money deducted status still shows. Refund reflect aagala, ID 77841.",
    expected_intent_id: "cancellation_refund",
    expected_lang: "Tamil",
    expected_order: "77841",
    expected_priority: "P1"
  },
  {
    id: "B21",
    text: "Sign in error coming continuous invalid passcode, verification OTP send pannunga mobile number ku.",
    expected_intent_id: "account_access",
    expected_lang: "Tamil",
    expected_order: null,
    expected_priority: "P2"
  },
  {
    id: "B22",
    text: "Box was completely crushed and damaged in transit, item totally faulty condition. Order 55102 replacement dispatch kijiye.",
    expected_intent_id: "damaged_item",
    expected_lang: "Hindi",
    expected_order: "55102",
    expected_priority: "P2"
  },
  {
    id: "B23",
    text: "Representative shouted at me on call and disconnect pannitanga abruptly. Escalate to manager immediately.",
    expected_intent_id: "agent_behaviour",
    expected_lang: "Tamil",
    expected_order: null,
    expected_priority: "P1"
  },
  {
    id: "B24",
    text: "Warranty card slip aur GST bill copy mail pe bhej do for claiming replacement, order 48211.",
    expected_intent_id: "document_request",
    expected_lang: "Hindi",
    expected_order: "48211",
    expected_priority: "P3"
  },
  {
    id: "B25",
    text: "Blue Dart tracking number shows no movement for a week, parcel kahan hai mera? Order 33417.",
    expected_intent_id: "delivery_delay",
    expected_lang: "Hindi",
    expected_order: "33417",
    expected_priority: "P2"
  },
  {
    id: "B26",
    text: "UPI payment do baar deduct ho gaya account se checkout timeout ke time. 1299 refund initiate karo, ID 99120.",
    expected_intent_id: "billing_dispute",
    expected_lang: "Hindi",
    expected_order: "99120",
    expected_priority: "P1"
  },
  {
    id: "B27",
    text: "Ami order cancel korechi kintu taka ekhono account e pending ache. Please check refund for order 77841.",
    expected_intent_id: "cancellation_refund",
    expected_lang: "Bengali",
    expected_order: "77841",
    expected_priority: "P1"
  },
  {
    id: "B28",
    text: "Cannot log in to customer app, password reset link expired error message display aagudhu. Send fresh link.",
    expected_intent_id: "account_access",
    expected_lang: "Tamil",
    expected_order: null,
    expected_priority: "P2"
  },
  {
    id: "B29",
    text: "Delivered product has swollen battery and physical defect, replace request arrange pannunga please. Order 55102.",
    expected_intent_id: "damaged_item",
    expected_lang: "Tamil",
    expected_order: "55102",
    expected_priority: "P2"
  },
  {
    id: "B30",
    text: "Agent ne bina help kiye direct call cut kar diya, extremely bad tone and misbehaviour from support side.",
    expected_intent_id: "agent_behaviour",
    expected_lang: "Hindi",
    expected_order: null,
    expected_priority: "P1"
  },
  {
    id: "B31",
    text: "Kindly share GST invoice copy and official payment receipt for purchase order 55102 to registered email.",
    expected_intent_id: "document_request",
    expected_lang: "English",
    expected_order: "55102",
    expected_priority: "P3"
  },
  {
    id: "B32",
    text: "Consignment dispatch aagi 5 days aachu but delivery courier tracking still not updated. Where is order 48211?",
    expected_intent_id: "delivery_delay",
    expected_lang: "Tamil",
    expected_order: "48211",
    expected_priority: "P2"
  },
  {
    id: "B33",
    text: "Bank statement la double charge show aagudhu for the same cart items. Refund amount to card, ID 99120.",
    expected_intent_id: "billing_dispute",
    expected_lang: "Tamil",
    expected_order: "99120",
    expected_priority: "P1"
  },
  {
    id: "B34",
    text: "Maine 3 din pehle item cancel kiya tha but amount still deducted dikha raha hai account statement me, 48211.",
    expected_intent_id: "cancellation_refund",
    expected_lang: "Hindi",
    expected_order: "48211",
    expected_priority: "P1"
  },
  {
    id: "B35",
    text: "Mobile app login blocked after wrong attempts, authentication verify karne ke liye reset passcode link bhej do.",
    expected_intent_id: "account_access",
    expected_lang: "Hindi",
    expected_order: null,
    expected_priority: "P2"
  },
  {
    id: "B36",
    text: "Package opened and found broken internal parts, replacement dispatch arrange kar do for order 55102.",
    expected_intent_id: "damaged_item",
    expected_lang: "Hindi",
    expected_order: "55102",
    expected_priority: "P2"
  },
  {
    id: "B37",
    text: "Last customer care person disconnected the call midway without resolving, unacceptable attitude and rude talk.",
    expected_intent_id: "agent_behaviour",
    expected_lang: "English",
    expected_order: null,
    expected_priority: "P1"
  },
  {
    id: "B38",
    text: "Tax invoice document download nahi ho raha hai website se, bill copy email kijiye order 33417 ka.",
    expected_intent_id: "document_request",
    expected_lang: "Hindi",
    expected_order: "33417",
    expected_priority: "P3"
  },
  {
    id: "B39",
    text: "Shadowfax courier courier delay aayirukku, 6 days tracking stuck at warehouse. Order 48211 eppo varum?",
    expected_intent_id: "delivery_delay",
    expected_lang: "Tamil",
    expected_order: "48211",
    expected_priority: "P2"
  },
  {
    id: "B40",
    text: "Wallet balance debited two times while placing order 99120, duplicate transaction paisa wapas chahiye.",
    expected_intent_id: "billing_dispute",
    expected_lang: "Hindi",
    expected_order: "99120",
    expected_priority: "P1"
  },
  {
    id: "B41",
    text: "Item cancellation done successfully yesterday kintu refund amount reflect hoyni bank e. ID 77841.",
    expected_intent_id: "cancellation_refund",
    expected_lang: "Bengali",
    expected_order: "77841",
    expected_priority: "P1"
  },
  {
    id: "B42",
    text: "Password reset OTP phone ku reach aagala, account completely locked, mudiyala to login.",
    expected_intent_id: "account_access",
    expected_lang: "Tamil",
    expected_order: null,
    expected_priority: "P2"
  },
  {
    id: "B43",
    text: "Scratch and broken glass panel received on device, defective product replacement exchange request for order 55102.",
    expected_intent_id: "damaged_item",
    expected_lang: "English",
    expected_order: "55102",
    expected_priority: "P2"
  },
  {
    id: "B44",
    text: "Executive was shouting during support call and hung up abruptly, severe misbehaviour issue.",
    expected_intent_id: "agent_behaviour",
    expected_lang: "English",
    expected_order: null,
    expected_priority: "P1"
  },
  {
    id: "B45",
    text: "Send official GST invoice and warranty registration slip to my email ID, order 48211.",
    expected_intent_id: "document_request",
    expected_lang: "English",
    expected_order: "48211",
    expected_priority: "P3"
  },
  {
    id: "B46",
    text: "Delivery boy phone karke bola parcel reach nahi hoga today, tracking shows delay for order 33417.",
    expected_intent_id: "delivery_delay",
    expected_lang: "Hindi",
    expected_order: "33417",
    expected_priority: "P2"
  },
  {
    id: "B47",
    text: "Netbanking la single order ku 2 times money debited. Duplicate charge refund status update pannunga, 99120.",
    expected_intent_id: "billing_dispute",
    expected_lang: "Tamil",
    expected_order: "99120",
    expected_priority: "P1"
  },
  {
    id: "B48",
    text: "Cancel kar chuka hoon order but refund credit pending in my account, deducted amount wapas kijiye for 48211.",
    expected_intent_id: "cancellation_refund",
    expected_lang: "Hindi",
    expected_order: "48211",
    expected_priority: "P1"
  },
  {
    id: "B49",
    text: "Account access blocked due to wrong credential entries, send verification link to registered email ID.",
    expected_intent_id: "account_access",
    expected_lang: "English",
    expected_order: null,
    expected_priority: "P2"
  },
  {
    id: "B50",
    text: "Parcel box kharab condition me mila, product broken tha inside. Immediate replacement chahiye for 55102.",
    expected_intent_id: "damaged_item",
    expected_lang: "Hindi",
    expected_order: "55102",
    expected_priority: "P2"
  },
  {
    id: "B51",
    text: "Customer executive was extremely rude, abusive language use kiya aur phone cut kar diya midway.",
    expected_intent_id: "agent_behaviour",
    expected_lang: "Hindi",
    expected_order: null,
    expected_priority: "P1"
  },
  {
    id: "B52",
    text: "GST bill copy and warranty document required for company reimbursement, email kar do order 33417.",
    expected_intent_id: "document_request",
    expected_lang: "Hindi",
    expected_order: "33417",
    expected_priority: "P3"
  }
];

/**
 * CodemixSkill Class — Middleware / Agent Skill
 */
class CodemixSkill {
  constructor(config = {}) {
    this.locales = config.locales || ["hi-IN", "ta-IN", "bn-IN", "en-IN"];
    this.stt = config.stt || "elevenlabs/scribe_v1";
    this.tts = config.tts || "elevenlabs/eleven_multilingual_v2";
    this.reply_in = config.reply_in || "caller_mix";
    this.record_in = config.record_in || "en";
    this.defaultModel = config.defaultModel || "gemini-3.6-flash";
    this.orders = Object.assign({}, CRM_ORDERS, config.orders || {});
  }

  /**
   * Identifies the Unicode script block of a given token.
   */
  static getScriptOf(token) {
    const match = INDIC_SCRIPTS.find(([, regex]) => regex.test(token));
    return match ? match[0] : null;
  }

  /**
   * Deterministic Tokenizer and Score-Based Intent Classifier (Offline Engine)
   */
  analyseOffline(utterance) {
    const rawTokens = utterance.match(/[\p{L}\p{M}\p{N}']+|[^\s\p{L}\p{M}\p{N}]/gu) || [];
    const detectedScripts = new Set();

    const tokens = rawTokens.map(token => {
      if (/^\p{N}+$/u.test(token)) return { t: token, l: "xx" };
      if (!/[\p{L}]/u.test(token)) return { t: token, l: "xx" };

      const script = CodemixSkill.getScriptOf(token);
      if (script) {
        detectedScripts.add(script);
        return { t: token, l: "hi" }; // Indic token
      }
      return { t: token, l: EN_WORDS.has(token.toLowerCase()) ? "en" : "hi" };
    });

    // Count intra-sentential switch boundaries
    let switchPoints = 0;
    let prevLang = null;
    tokens.forEach(k => {
      if (k.l === "hi" || k.l === "en") {
        if (prevLang && prevLang !== k.l) switchPoints++;
        prevLang = k.l;
      }
    });

    const idMatch = utterance.match(/\b(\d{5})\b/);
    const orderId = idMatch ? idMatch[1] : null;

    // Score-based Intent Resolution with Precise Word Boundaries
    let bestIntent = null;
    let highestScore = 0;

    INTENT_RULES.forEach(rule => {
      let score = 0;
      rule.weights.forEach(group => {
        const matched = group.kw.some(kw => {
          // Native Indic script characters
          if (/[\u0900-\u0D7F]/.test(kw)) return utterance.includes(kw);
          // Word boundary matching for Latin / English words
          const escaped = kw.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
          const wordBoundaryRegex = new RegExp(`(^|[^\\p{L}\\p{N}])` + escaped + `($|[^\\p{L}\\p{N}])`, "iu");
          return wordBoundaryRegex.test(utterance);
        });
        if (matched) score += group.w;
      });

      if (score > highestScore) {
        highestScore = score;
        bestIntent = rule;
      }
    });

    // Fallback if no specific rule threshold met
    let intentName = "General customer support inquiry";
    let intentAction = "Review ticket and route to support agent";
    let intentPriority = "P3";
    let intentSubject = "Customer support inquiry";
    let intentId = "general_support";

    if (bestIntent && highestScore >= 3) {
      intentName = bestIntent.name;
      intentAction = bestIntent.action;
      intentPriority = bestIntent.priority;
      intentSubject = bestIntent.subject;
      intentId = bestIntent.id;
    }

    // Sentiment detection
    const isAngry = /\b(complaint|scene|yaar|kova|kovam|ghussa|bakwaas|fraud|worst|terrible|horrible|cheated|robbery|rude|abuse|unacceptable)\b/i.test(utterance) ||
      /(?:[\u0B80-\u0BFF]*?)(?:கோவ|கோபம்|வெறி)|गुस्सा|क्रोध|খারাপ/.test(utterance);
    const sentiment = isAngry ? "frustrated" : "concerned";

    // Dialect Identification Heuristics (Latin transliterations)
    const lowerUtterance = " " + utterance.toLowerCase() + " ";
    const TA_RE = /\b(enna|panna|pannunga|pannen|vendum|venum|mudiyala|vandhu|aayiduchu|irukku|seri|romba|konjam|epdi|eppo|enga|sollunga|paakanum|thala|anna|naan|neenga|ille|illa|nalla|tharen|anuppuren|ippo|aachu|pannitanga|kitta|pesanum|varudhu|therila|irukaru|thevai|vidunga|aayirukku)\b/i;
    const BN_RE = /\b(ami|tumi|apni|ache|kore|hocche|kintu|ekhon|keno|kothay|bhalo|hoyeche|korechi|ferot|porjonto|hoyni|eta|theke|geche|korechilam|dilo|baje)\b/i;
    const MR_RE = /\b(mala|tula|ahe|kay|kasa|kuthe|ata|pan|nahi zala|zala|kela)\b/i;
    const HI_RE = /\b(mera|meri|mere|main|mujhe|aap|aapne|nahi|nahin|hai|hua|raha|rahi|kar|kiya|abhi|kal|aaj|bhi|koi|kya|ye|yeh|bhaiya|yaar|se|ko|ka|ki|ke|phir|maine|karunga|dijiye|jaldi|chahiye|turant|dekha|tha|bhej|mila|chori|raste|hoga|hafta)\b/i;

    let detectedIndic = null;
    if (detectedScripts.size > 0) detectedIndic = [...detectedScripts][0];
    else if (TA_RE.test(lowerUtterance)) detectedIndic = "Tamil";
    else if (BN_RE.test(lowerUtterance)) detectedIndic = "Bengali";
    else if (MR_RE.test(lowerUtterance)) detectedIndic = "Marathi";
    else if (HI_RE.test(lowerUtterance)) detectedIndic = "Hindi";

    const languages = detectedIndic ? [detectedIndic, "English"] : ["English"];
    const orderData = orderId ? this.orders[orderId] : null;

    // Mixed-language reply synthesis
    let replyMixed = "";
    if (detectedScripts.size > 0 && detectedIndic === "Tamil") {
      replyMixed = `சாரி boss, நான் check பண்ணேன் — உங்க ${orderId ? `order ${orderId}` : `account`} issue எனக்கு புரியுது. நான் இப்போ escalate பண்றேன், two minutes ல update தர்றேன்.`;
    } else if (detectedScripts.size > 0 && (detectedIndic === "Hindi" || detectedIndic === "Marathi")) {
      replyMixed = `माफ़ कीजिए भैया, मैंने check किया — ${orderId ? `order ${orderId}` : `आपका issue`} मैं अभी escalate कर रहा हूँ, आज ही update मिलेगा।`;
    } else if (detectedIndic === "Tamil") {
      replyMixed = orderData
        ? `Sorry boss, naan check pannen — order ${orderId} ${orderData.status}. Naan immediate action arrange panren, update udane varum.`
        : `Seri boss, naan check panren. Two minutes la ungakku update tharen.`;
    } else if (detectedIndic === "Hindi") {
      replyMixed = orderData
        ? `Sorry hua bhaiya. Maine check kiya — order ${orderId} ${orderData.status}. Main abhi arrange kar raha hoon, aaj hi update milega.`
        : `Bilkul, main abhi check kar raha hoon. Ek minute dijiye, main aapko exact status batata hoon.`;
    } else if (detectedIndic === "Bengali") {
      replyMixed = orderData
        ? `Dukkhoito, ami check korechi — order ${orderId} ${orderData.status}. Ami ekhoni escalation korchi, update peye jaben.`
        : `Ami check korchi, ekdom chinta korben na. Ekhoni update dicchi.`;
    } else {
      replyMixed = `Thanks for waiting — I have verified this and initiated the resolution. You will receive an update today.`;
    }

    const summary = `Customer reported: ${intentName.toLowerCase()}.` +
      (orderId ? ` Order reference ${orderId}${orderData ? `, currently ${orderData.status}` : ``}.` : ` No order reference given.`) +
      ` Customer sounds ${sentiment}. Spoke in ${languages.join(" mixed with ")}.`;

    return {
      intent_id: intentId,
      intent_score: highestScore,
      tokens,
      languages,
      switch_points: switchPoints,
      intent: intentName,
      entities: {
        order_id: orderId,
        sentiment,
        urgency: intentPriority === "P1" ? "high" : intentPriority === "P2" ? "medium" : "low"
      },
      confidence: switchPoints > 2 ? "high" : "medium",
      reply_mixed: replyMixed,
      ticket_en: {
        subject: intentSubject,
        summary,
        action: intentAction,
        priority: intentPriority
      }
    };
  }

  /**
   * Live Gemini Analysis with Exponential Backoff
   */
  async analyseLive(utterance, apiKey, model = null) {
    if (!apiKey) throw new Error("no key");
    const targetModel = (model || this.defaultModel).replace(/^models\//, "");

    const promptText = `You analyse code-mixed Indian customer support speech.

Utterance: """${utterance}"""

Return ONLY JSON, no markdown fences:
{"tokens":[{"t":"word","l":"hi"|"en"|"xx"}],
 "languages":["Hindi","English"],
 "switch_points":<integer>,
 "intent":"<short English intent, max 8 words>",
 "entities":{"order_id":"<digits or null>","sentiment":"<one word>","urgency":"low|medium|high"},
 "confidence":"high|medium|low",
 "reply_mixed":"<one reply in the SAME mix the caller used, max 30 words>",
 "ticket_en":{"subject":"<English, max 9 words>","summary":"<2-3 plain English sentences>","action":"<English, max 10 words>","priority":"P1|P2|P3"}}
Rules: "l" is "hi" for ANY Indic-language word written in Latin script (Hindi, Tamil, Telugu, Bengali, Marathi, Kannada, Malayalam), "en" for English, "xx" for punctuation and numbers. Keep every token in order. Name the actual Indic language in "languages". reply_mixed mirrors the caller's mixing, it does not translate to one language.`;

    let response, lastError = "";
    for (let attempt = 0; attempt < 3; attempt++) {
      if (attempt > 0) {
        await new Promise(res => setTimeout(res, 1200 * attempt * attempt));
      }

      response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(targetModel)}:generateContent`, {
        method: "POST",
        headers: { "Content-Type": "application/json", "x-goog-api-key": apiKey },
        body: JSON.stringify({
          contents: [{ role: "user", parts: [{ text: promptText }] }],
          generationConfig: { responseMimeType: "application/json", maxOutputTokens: 8192 }
        })
      });

      if (response.ok) break;

      try {
        const errData = await response.clone().json();
        lastError = (errData && errData.error && errData.error.message) || `Status ${response.status}`;
      } catch (_err) {
        lastError = `Status ${response.status}`;
      }

      if (response.status === 404) {
        throw new Error(`Gemini 404: Model "${targetModel}" was not found or is unavailable for this API key. Please check the model name (e.g., gemini-3.6-flash).`);
      }

      if (response.status !== 503 && response.status !== 429) break;
    }

    if (!response.ok) throw new Error(`Gemini ${response.status} — ${lastError}`);
    const data = await response.json();
    const candidate = data.candidates && data.candidates[0];
    if (!candidate) throw new Error("Gemini returned no candidate response");

    const textContent = (candidate.content && candidate.content.parts || [])
      .filter(part => !part.thought)
      .map(part => part.text || "")
      .join("");

    if (!textContent.trim()) throw new Error("Gemini returned an empty reply");

    try {
      return JSON.parse(textContent.replace(/```json|```/g, "").trim());
    } catch (_err) {
      throw new Error("Gemini did not return valid JSON");
    }
  }

  /**
   * Resilient merge overlay
   */
  static merge(live, base) {
    const isValid = v => v !== undefined && v !== null && v !== "";
    const merged = JSON.parse(JSON.stringify(base));

    if (Array.isArray(live.tokens) && live.tokens.length) merged.tokens = live.tokens;
    if (Array.isArray(live.languages) && live.languages.length) merged.languages = live.languages;
    if (typeof live.switch_points === "number") merged.switch_points = live.switch_points;
    if (isValid(live.intent)) merged.intent = live.intent;

    if (live.entities) {
      if (isValid(live.entities.order_id)) merged.entities.order_id = live.entities.order_id;
      if (isValid(live.entities.sentiment)) merged.entities.sentiment = live.entities.sentiment;
      if (isValid(live.entities.urgency)) merged.entities.urgency = live.entities.urgency;
    }
    if (isValid(live.confidence)) merged.confidence = live.confidence;
    if (isValid(live.reply_mixed)) merged.reply_mixed = live.reply_mixed;

    if (live.ticket_en) {
      if (isValid(live.ticket_en.subject)) merged.ticket_en.subject = live.ticket_en.subject;
      if (isValid(live.ticket_en.summary)) merged.ticket_en.summary = live.ticket_en.summary;
      if (isValid(live.ticket_en.action)) merged.ticket_en.action = live.ticket_en.action;
      if (isValid(live.ticket_en.priority)) merged.ticket_en.priority = live.ticket_en.priority;
    }
    return merged;
  }

  /**
   * Evaluates a dataset and calculates Intent, Entity, and Language accuracy
   */
  evaluateDataset(dataset) {
    let intentMatches = 0;
    let entityMatches = 0;
    let langMatches = 0;
    let totalLatencyMs = 0;

    const detailedResults = dataset.map(item => {
      const startTime = performance.now();
      const result = this.analyseOffline(item.text);
      const latency = performance.now() - startTime;
      totalLatencyMs += latency;

      const intentPassed = result.intent_id === item.expected_intent_id;
      const orderPassed = (result.entities.order_id || null) === (item.expected_order || null);
      const predictedPrimaryLang = result.languages && result.languages[0] ? result.languages[0].toLowerCase() : "";
      const expectedPrimaryLang = item.expected_lang ? item.expected_lang.toLowerCase() : "";
      const langPassed = predictedPrimaryLang === expectedPrimaryLang;

      if (intentPassed) intentMatches++;
      if (orderPassed) entityMatches++;
      if (langPassed) langMatches++;

      return {
        id: item.id,
        utterance: item.text,
        expectedIntent: item.expected_intent_id,
        predictedIntent: result.intent_id,
        intentPassed,
        expectedOrder: item.expected_order,
        predictedOrder: result.entities.order_id,
        orderPassed,
        expectedLang: item.expected_lang,
        predictedLang: result.languages[0] || "English",
        langPassed,
        languages: result.languages,
        switchPoints: result.switch_points,
        latencyMs: Math.round(latency * 100) / 100
      };
    });

    const intentAccuracy = Math.round((intentMatches / dataset.length) * 100);
    const entityAccuracy = Math.round((entityMatches / dataset.length) * 100);
    const langAccuracy = Math.round((langMatches / dataset.length) * 100);
    const avgLatency = Math.round((totalLatencyMs / dataset.length) * 100) / 100;

    return {
      total: dataset.length,
      intentMatches,
      intentAccuracy: `${intentAccuracy}%`,
      entityMatches,
      entityAccuracy: `${entityAccuracy}%`,
      langMatches,
      langAccuracy: `${langAccuracy}%`,
      avgLatencyMs: avgLatency,
      results: detailedResults
    };
  }

  /**
   * Runs the complete Benchmark Suite
   */
  runBenchmark(customDataset = null) {
    if (customDataset) {
      return this.evaluateDataset(customDataset);
    }

    const tunedResults = this.evaluateDataset(BENCHMARK_DATASET);
    const extendedResults = this.evaluateDataset(HELD_OUT_DATASET);
    const blindResults = this.evaluateDataset(BLIND_DATASET);

    return {
      tuned: tunedResults,
      extended: extendedResults,
      blind: blindResults,
      total: tunedResults.total,
      intentMatches: tunedResults.intentMatches,
      intentAccuracy: tunedResults.intentAccuracy,
      entityMatches: tunedResults.entityMatches,
      entityAccuracy: tunedResults.entityAccuracy,
      langMatches: tunedResults.langMatches,
      langAccuracy: tunedResults.langAccuracy,
      avgLatencyMs: tunedResults.avgLatencyMs,
      results: tunedResults.results
    };
  }
}

// Universal Global Attachment (for Browser Scripts)
if (typeof window !== "undefined") {
  window.CodemixSkill = CodemixSkill;
  window.CRM_ORDERS = CRM_ORDERS;
  window.BENCHMARK_DATASET = BENCHMARK_DATASET;
  window.HELD_OUT_DATASET = HELD_OUT_DATASET;
  window.BLIND_DATASET = BLIND_DATASET;
  window.INTENT_RULES = INTENT_RULES;
  window.EN_WORDS = EN_WORDS;
}
if (typeof globalThis !== "undefined") {
  globalThis.CodemixSkill = CodemixSkill;
  globalThis.CRM_ORDERS = CRM_ORDERS;
  globalThis.BENCHMARK_DATASET = BENCHMARK_DATASET;
  globalThis.HELD_OUT_DATASET = HELD_OUT_DATASET;
  globalThis.BLIND_DATASET = BLIND_DATASET;
  globalThis.INTENT_RULES = INTENT_RULES;
  globalThis.EN_WORDS = EN_WORDS;
}

module.exports = {
  CodemixSkill,
  CRM_ORDERS,
  BENCHMARK_DATASET,
  HELD_OUT_DATASET,
  BLIND_DATASET,
  INTENT_RULES,
  EN_WORDS,
  default: CodemixSkill
};
