/**
 * Codemix Skill — CommonJS Artifact Generator
 * Reads the single source of truth (codemix.js) and produces codemix.cjs
 * for CommonJS runtimes, preventing code drift.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import assert from "node:assert/strict";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const srcPath = path.join(rootDir, "codemix.js");
const destPath = path.join(rootDir, "codemix.cjs");

const src = fs.readFileSync(srcPath, "utf-8");

// Guard 1: Fail loudly if codemix.js contains top-level imports
if (/^\s*import\s+/m.test(src)) {
  console.error("[build:cjs ERROR] codemix.js contains top-level import statements. Cannot generate CJS.");
  process.exit(1);
}

// Guard 2: Fail loudly if codemix.js contains import.meta
if (/import\.meta/.test(src)) {
  console.error("[build:cjs ERROR] codemix.js contains import.meta. Cannot generate CJS.");
  process.exit(1);
}

// Replace header comment with required generation notice
let cjs = src.replace(
  /\/\*\*[\s\S]*?Codemix Skill — Core Engine[\s\S]*?\*\//,
  `// GENERATED by scripts/build-cjs.js — DO NOT EDIT. Source of truth: codemix.js\n/**\n * Codemix Skill — CommonJS Engine & Module\n * Generated automatically from codemix.js (Single Source of Truth).\n */`
);

// Replace ES module exports at bottom with CommonJS module.exports
cjs = cjs.replace(
  /\/\/ Export for modern ES Module environments[\s\S]*?export default CodemixSkill;\s*$/,
  `module.exports = {
  CodemixSkill,
  CRM_ORDERS,
  BENCHMARK_DATASET,
  HELD_OUT_DATASET,
  BLIND_DATASET,
  INTENT_RULES,
  EN_WORDS,
  default: CodemixSkill
};
`
);

// Enforce LF line endings
cjs = cjs.replace(/\r\n/g, "\n");

fs.writeFileSync(destPath, cjs, { encoding: "utf-8" });

// Self-check after generating: load both ESM and CJS and verify parity
const esmModule = await import(`file://${srcPath.replace(/\\/g, "/")}?t=${Date.now()}`);
const require = createRequire(import.meta.url);
const cjsModule = require(destPath);

// 1. Verify export surfaces match
const expectedExports = ["CodemixSkill", "CRM_ORDERS", "BENCHMARK_DATASET", "HELD_OUT_DATASET", "BLIND_DATASET", "INTENT_RULES", "EN_WORDS"];
for (const exp of expectedExports) {
  assert.ok(exp in esmModule, `ESM export missing: ${exp}`);
  assert.ok(exp in cjsModule, `CJS export missing: ${exp}`);
}

// 2. Behavioral smoke test parity
const smokeUtterance = "Bhaiya mera order 48211 abhi tak deliver nahi hua, tracking bhi update nahi ho raha hai.";
const esmSkill = new esmModule.CodemixSkill();
const cjsSkill = new cjsModule.CodemixSkill();
const esmRes = esmSkill.analyseOffline(smokeUtterance);
const cjsRes = cjsSkill.analyseOffline(smokeUtterance);

assert.deepStrictEqual(esmRes, cjsRes, "ESM and CJS analysis outputs must be deep-equal");

console.log(`[build:cjs] Successfully synced codemix.cjs from codemix.js (${cjs.length} bytes, LF line endings)`);
console.log(`[build:cjs] Self-check passed: export-surface and behavioral parity verified.`);
